### ISSUE TITLE
How to use PM2 to Run Node.js Apps on a VPS

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#22]
As a node.js developer wanting to deploy a web app to !Heroku 
I need a way to deploy and run my App on a "commodity" VPS.

# Todo

+ [x] _Automatically deploy_ from CI to Digital Ocean VPS (_we will demo other providers later_)
+ [x] Use GitHub Deploy Keys on the Server to **`git pull`**  from GH.
  see: https://developer.github.com/v3/guides/managing-deploy-keys
+ [x] NPM install the latest dependencies
+ [x] Use PM2 to restart the Server once latest dependencies installed.

## Reading

+ https://mrvautin.com/running-nodejs-applications-in-production-forever-vs-supervisord-vs-pm2/

**Comment by gregtandiono** [comment]
Yeah, i'd go with [pm2](https://github.com/Unitech/pm2), because they have the monitoring service baked in with the package, and you init the monitor from within the instance. (And they have load balancing too, via `cluster mode`)

**Comment by nelsonic** [comment]
@gregtandiono _currently_ using `forever` with https://hits.dwyl.com
Would _prefer_ to be using https://github.com/tableflip/guvnor but sadly I think it's "_mothballed_".

**Comment by nelsonic** [comment]
Anyone wanting Zero Downtime Continuous Deployment from CI (e.g: TravisCI/CircleCI/CodeShip)
using PM2, see: https://github.com/dwyl/learn-devops/blob/master/nodejs-pm2-zero-downtime.md
