### ISSUE TITLE
Deploying App(s) to Digital Ocean using Dokku

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#24]
@iteles in `case` you're _wondering_ why I'm "working late" today ... 
I'm working on "Staging" Continuous (_Automatic_) Deployment for CI. 🚀 

But I don't want to create "noise" on the "official" issue, instead I will just create a PR _here_ 
(_so that other people can benefit from the knowledge_)
and then when it's all _working_ I will copy over the "how-to" as "documentation" for the project.

+ [x] Writeup how to deploy _multiple_ apps to the _same_ VM/instance
+ [x] Setup & Use a Let's Encrypt Wildcard SSL certificate #28 
+ [x] Create a `new` App for the _current Git branch_ #30

**Comment by nelsonic** [comment]
Totes done. See: https://github.com/dwyl/learn-devops/blob/master/nodejs-digital-ocean-centos-dokku.md
