### ISSUE TITLE
How to Auto-Renew Let's Encrypt SSL Certificate?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#44]
We have a _few_ projects which use Let's Encrypt SSL Certificates and I intend to _continue_ using them.

## Tasks

+ [ ] Research, document & implement certificate renewal for:
  + [ ] hits.dwyl.io (Debian)
  + [ ] ademo.app #43 (Centos)

I feel like this should be a _standalone_ `.md` file similar to:
https://github.com/dwyl/learn-devops/blob/master/letsencrypt-wildcard-certificate.md

> Starting point: https://community.letsencrypt.org/search?q=auto

related to: https://github.com/dwyl/learn-devops/issues/43
required by: https://github.com/dwyl/learn-travis/issues/45

**Comment by nelsonic** [comment]
_manually_ renewed for *.ademo.app (_wildcard onlyl_)
![image](https://user-images.githubusercontent.com/194400/44779166-06ea1300-ab7f-11e8-91b1-723be4ce40bd.png)

**Comment by nelsonic** [comment]
Was: https://hello.ademo.app
![image](https://user-images.githubusercontent.com/194400/44780841-326efc80-ab83-11e8-8be9-b5a8eb82d6be.png)

Re-deployed:
![image](https://user-images.githubusercontent.com/194400/44780813-2125f000-ab83-11e8-9f8c-fbae58353e80.png)

Now:
![image](https://user-images.githubusercontent.com/194400/44780852-3b5fce00-ab83-11e8-8cd5-42e7502f8db7.png)

Note: this is still _not_ automated! it was just to "unblock" progress on https://github.com/charterindex/application/pull/444
