### ISSUE TITLE
Upgrade Linode Instance to Avoid 502 on Hits

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#52]
# Todo 

+ [x] Login to Linode
  + [x] Increase instance from current $5/month to $10/month (_double disk space_)
+ [x] ssh to restart the instance/app
+ [x] test service has resumed

related to https://github.com/dwyl/hits/issues/62

**Comment by nelsonic** [comment]
The disk space is not even exhausted yet ... 😕 
![image](https://user-images.githubusercontent.com/194400/56297168-c21fe600-6127-11e9-88dc-f923cf07618c.png)

Going to upgrade it and restart the server in any case.

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/56297363-1aef7e80-6128-11e9-9519-a06d2dafd2ba.png)

![image](https://user-images.githubusercontent.com/194400/56297398-280c6d80-6128-11e9-9379-6569a71d153b.png)

![image](https://user-images.githubusercontent.com/194400/56297437-38244d00-6128-11e9-850e-c501bfae811f.png)

![image](https://user-images.githubusercontent.com/194400/56297460-46726900-6128-11e9-982e-18fde06ccf78.png)

![image](https://user-images.githubusercontent.com/194400/56297561-7588da80-6128-11e9-8f7b-7a479698fb19.png)

![image](https://user-images.githubusercontent.com/194400/56297689-b680ef00-6128-11e9-9c2a-1b225197eb8e.png)

![image](https://user-images.githubusercontent.com/194400/56298075-6eae9780-6129-11e9-9350-eb19d9cee6ac.png)

![image](https://user-images.githubusercontent.com/194400/56298105-7d954a00-6129-11e9-8fec-8b7fc97e3615.png)

Backups are $2.50/month ...
![image](https://user-images.githubusercontent.com/194400/56298157-930a7400-6129-11e9-96de-c39e3c26dd66.png)

Enabling. 

![image](https://user-images.githubusercontent.com/194400/56298199-a4ec1700-6129-11e9-97f1-84dbc531aa1f.png)

![image](https://user-images.githubusercontent.com/194400/56298317-da910000-6129-11e9-9be3-c25ffb46b394.png)


![image](https://user-images.githubusercontent.com/194400/56298392-f98f9200-6129-11e9-8f1c-19ad22ac864c.png)


```sh
cd hits
forever start server.js
```

Done. ✅ 

Current Git revision: commit 0a44edd692b5b765c20c85ed4057a50bbd872507
![image](https://user-images.githubusercontent.com/194400/56300323-a7e90680-612d-11e9-84f1-9fc4ec67c470.png)
Matches latest `master` https://github.com/dwyl/hits/commits/master
![image](https://user-images.githubusercontent.com/194400/56300417-d7980e80-612d-11e9-899a-c3d7ce87b096.png)


![image](https://user-images.githubusercontent.com/194400/56300477-f26a8300-612d-11e9-8402-638809eda973.png)
