### ISSUE TITLE
Linode Billing/Invoice (Paying for inactive instances) 💸 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#62]
This month's Linode invoice includes 3 instances we don't _need_ to be paying for:

![linode-invoice-showing-4-instance](https://user-images.githubusercontent.com/194400/87330086-f1dabb00-c52f-11ea-89ee-4ffd710e766b.png)

The only App we have running on Linode is Hits which is [**`178.79.141.232`**](http://178.79.141.232) 
![linode-dashboard-showing-instances](https://user-images.githubusercontent.com/194400/87331595-22235900-c532-11ea-8cf9-e5808261ea48.png)

But we are _paying_ for 4 instances: https://cloud.linode.com/linodes
***idle*** instances are still charged at full price because they "reserve" the resources for it. 🙄 

https://www.linode.com/docs/platform/billing-and-support/billing-and-payments/#if-my-linode-is-powered-off-will-i-be-billed
![image](https://user-images.githubusercontent.com/194400/87335066-96143000-c537-11ea-9a3d-624cbb2bad8d.png)

Given that we only need a "**nano**" instance if we use Postgres instead of the file system,
we could get our monthly cost of running Hits down to **$6/month** if we use off-instance backup using rsync. 

# Todo

+ [ ] Copy the data from the `185.3.95.195` instance so we can **`delete`** it. 
https://www.linode.com/docs/platform/disk-images/copying-a-disk-image-over-ssh
+ [ ] Migrate data from `178.79.141.232` to a Phoenix version of Hits

+ [ ] Determine if we still need `80.85.86.32` (offline) and `151.236.220.56` (running) 
  > @SimonLab can you take a look at this when you are back from your leave? 
  > Related to: #59 & #61

**Comment by nelsonic** [comment]
Received a warning that "maintenance is required" for all our Linode instances. 
https://cloud.linode.com/support/tickets/14202915
![image](https://user-images.githubusercontent.com/194400/87930665-6194fc80-ca80-11ea-9efc-310c8b15a98b.png)

https://cloud.linode.com/dashboard
![image](https://user-images.githubusercontent.com/194400/87928142-3b6d5d80-ca7c-11ea-967b-d5596f0bffb1.png)
That means they will reboot the instances. 😕 
I want to **`DELETE`** all the Linode instances before the maintenance. ✂️ 
The concept of having to pay for an idle instance is absurd to me. 💸 

The fact that Linode Block Storage is based on _spinning_ disks (HDD) see: https://github.com/dwyl/learn-devops/issues/58#issuecomment-660654332 
means that I'm migrating Hits to use DigitalOcean which has **NVMe SSD block storage** (_**10-40x faster** seek time!_)

**Comment by nelsonic** [comment]
No longer an issue. Closing. ✅
