### ISSUE TITLE
How to copy data from Linode VPS instance (SSD) to Block Storage?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#63]
As part of #59 we need to migrate the data on our _existing_ instances to _temporary_ Block Storage so that we can kill the instances and save on costs #62. 

# Todo

+ [ ] Investigate how to do this!
+ [ ] Write up _every_ step so that it can be re-performed by anyone else in 1/10 the time.
+ [ ] perform the copy on our Hits instances
+ [ ] check the data is there!
+ [ ] Shut down the Hits instances after new deployment #58  & #59
