### ISSUE TITLE
How to avoid SSH Timeout when downloading large or lots of files?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#73]
When attempting to download a large file (or set of files) over SSH (e.g. to Backup/Migrate a VM),
the SSH Connection times-out and I have to restart the process. 🤦 

I need to refresh my memory on how to do this. 

# Todo

+ [x] ~~Configure the VM to not Timeout SSH Connections~~
+ [x] Configure iTerm to not timeout SSH -> `echo "ServerAliveInterval 60" >> ~/.ssh/config`
+ [x] Set Mac to not sleep when plugged in to power 🍏 

This should only take a few mins of googling and reading, but i need to document it. 📝 

This is a subtask of https://github.com/dwyl/hits/issues/81  which in turn will un-block https://github.com/dwyl/hits/issues/117 and https://github.com/dwyl/hits/issues/101 etc.

**Comment by nelsonic** [comment]
System Preferences > **Energy Saver** settings on Mac: "**Computer sleep: _Never_**"
![image](https://user-images.githubusercontent.com/194400/119235491-b6832280-bb2a-11eb-8a63-ea3605325d56.png)

**Comment by nelsonic** [comment]
This looks like what I need: https://superuser.com/questions/699676/how-to-prevent-ssh-from-disconnecting

Edit your `~/.ssh/config` file on your Mac (`localhost`) and add the following line:

```sh
ServerAliveInterval 60
```

**Comment by nelsonic** [comment]
Fail:
![linode-requires-javascript](https://user-images.githubusercontent.com/194400/119241607-a7fb3200-bb4f-11eb-834f-64338e237022.png)

**Comment by nelsonic** [comment]
185.3.95.195 178.79.141.232

**Comment by lukeeey** [comment]
Good to see you're still working on this 👍

**Comment by nelsonic** [comment]
Hi @lukeeey, 👋  
Indeed ... 👨‍💻 ⏳

**Comment by nelsonic** [comment]
Ok, this seems to be working without needing to update anything on the VMs, just the `ServerAliveInterval 60` in `~/.ssh/config` on `localhost` is enough to keep the connection alive provided the Mac stays on. 

I'm using an _ancient_ (in computer terms) Mac Mini to backup the VMs:
![Screen Shot 2021-05-23 at 7 19 08 AM](https://user-images.githubusercontent.com/194400/119250316-2fb85f00-bb97-11eb-852e-f429e981abb6.png)

and I left it on overnight downloading all the files from the two VMs. Switched off the screen to not waste energy, but the Mac Mini stayed on doing happily doing it's thing.
I know I could use a Raspberry Pi Zero to do this task, I don't need an Intel i5 ... but this computer is "free" so I'm using it.
