### ISSUE TITLE
Gogs: Document `localhost` Setup (Docker) + Fly.io Deployment

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#79]
As noted in https://github.com/dwyl/github-backup/issues/136 we are considering using `Gogs` as a Backup Git/GitHub server.

This could potentially be a "core" element of our infrastructure at least from a Business Continuity perspective.
So we need to have our SPIKE to set it up well-documented so it can be replicated & maintained. 

# Todo

+ [x] Install `Gogs` on Raspberry Pi 4. Requires: https://github.com/dwyl/learn-devops/issues/80
  + [x] Play around with it and see what features it has.
+ [x] Deploy to Fly.io with lowest possible resources.
+ [x] Figure out how to secure it. (read docs!)

## Context

For context: my plan with setting up a **`Gogs`** server is to piggy-back on the hard work done by the community in terms of creating a (simplified) **`Clone`** of **GitHub** that we can use to mirror all our projects. I feel this is a _very_ worthwhile task and if we use **`Postgres`** as the DB for **`Gogs`** we can attempt to connect to it from **`Phoenix`** and thus we have _most_ of the [**`Tudo`**](https://github.com/dwyl/tudo) App.

**Comment by nelsonic** [comment]
Borrowing the homepage logo for the doc:
![image](https://user-images.githubusercontent.com/194400/162528448-5df0e9e8-a132-4644-b216-5107e0df0204.png)

**Comment by SimonLab** [comment]
Gogs provides a REST API: https://github.com/gogs/docs-api/tree/master/Repositories

I think it's possible to create a new repository via the API (https://github.com/gogs/docs-api/tree/master/Repositories#create) however other commands (create commits, create branches) don't seem to be available or at least documented.
@nelsonic I know you looked at using Gogs as a local server, did you look at the API at the same time?

**Comment by SimonLab** [comment]
# Phx +  Git + Fly.io

I wanted to tests the idea of deploying a Phoenix application on Fly.io where Git is also installed along the application.

**Comment by nelsonic** [comment]
During the initial setup on the `Raspberry Pi`, when you first run the `Gogs` web server:

```
./gogs web
```

You will be instructed to visit http://0.0.0.0:3000 ...

In my case I'm running the PI as a Server 
so I need to access the IP address on my Mac http://192.168.1.196:3000 (on the same network ...)

![image](https://user-images.githubusercontent.com/194400/162982227-2ce4f772-d574-4ba7-af59-a66df1dddc60.png)

Use the IP address for the PI as the Application URL: http://192.168.1.196:3000/

![image](https://user-images.githubusercontent.com/194400/162982781-18fc0a35-7bd3-405e-ba17-6dac8dcb1320.png)


Once configured, created a new user and repo: http://192.168.1.196:3000/nelsonic/my-awesome-repo
![image](https://user-images.githubusercontent.com/194400/163005975-2a2abefa-11a5-4085-96b8-133c8a28f587.png)

The Markdown Editor is functional:
http://192.168.1.196:3000/nelsonic/my-awesome-repo/_edit/master/README.md
![image](https://user-images.githubusercontent.com/194400/163045863-d06be897-30e3-4b47-8282-49417e37c175.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/163057616-1bd02d41-342d-4fac-a6b6-8fb3e3e11134.png)

![image](https://user-images.githubusercontent.com/194400/163059605-be133880-42dc-4794-920e-af6230fca4bc.png)

**Comment by nelsonic** [comment]
I've done a bunch of testing of Gogs on my local Raspberry Pi instance. ✅ 

Now trying to deploy a "Production" instance on Fly.io 🚀 

Sadly, the Appkata: Gogs https://fly.io/docs/app-guides/git-gogs-server/ is "broken". 💔 
Linked to from: [/app-guides/git-gogs-server.html.erb#L7](https://github.com/superfly/docs/blob/ef188f3318dd1286e08f44674803f32f8d6870f5/app-guides/git-gogs-server.html.erb#L7)

`flyctl init` gives the following error:

```sh
Error: unknown command "init" for "flyctl"

Did you mean this?
	info
```

The source: https://github.com/fly-apps/appkata-gogs/ "has been archived" ... 
i.e. we cannot submit a PR to update it. 🤦‍♂️ 

Ran the command:
```sh
flyctl launch --name gogs-server --image gogs/gogs --org dwyl
```

Got the following output/error:

```sh
1 desired, 1 placed, 0 healthy, 1 unhealthy [health checks: 1 total, 1 critical]
v0 failed - Failed due to unhealthy allocations - no stable job version to auto revert to
Failed Instances

==> Failure #1

Instance
  ID            = 70063cfa
  Process       =
  Version       = 0
  Region        = lhr
  Desired       = run
  Status        = running
  Health Checks = 1 total, 1 critical
  Restarts      = 0
  Created       = 4m50s ago

Recent Events
TIMESTAMP            TYPE       MESSAGE
2022-04-22T00:20:04Z Received   Task received by client
2022-04-22T00:20:04Z Task Setup Building Task Directory
2022-04-22T00:20:13Z Started    Task started by client

Recent Logs
2022-04-22T00:25:04.000 [info] chmod: /data/ssh/*: No such file or directory
2022-04-22T00:25:04.000 [info] Unable to load host key: /data/ssh/ssh_host_rsa_key
2022-04-22T00:25:04.000 [info] Unable to load host key: /data/ssh/ssh_host_dsa_key
2022-04-22T00:25:04.000 [info] Unable to load host key: /data/ssh/ssh_host_ecdsa_key
2022-04-22T00:25:04.000 [info] Unable to load host key: /data/ssh/ssh_host_ed25519_key
2022-04-22T00:25:04.000 [info] sshd: no hostkeys available -- exiting.
2022-04-22T00:25:04.000 [info] mkdir: can't create directory '/data/': Permission denied
2022-04-22T00:25:04.000 [info] chmod: /data/git/.ssh: No such file or directory
2022-04-22T00:25:04.000 [info] ./run: ./setup: line 9: can't create /data/git/.ssh/environment: nonexistent directory
2022-04-22T00:25:04.000 [info] chmod: /data/git/.ssh/environment: No such file or directory
2022-04-22T00:25:04.000 [info] chmod: /data: No such file or directory
2022-04-22T00:25:04.000 [info] chmod: /data/gogs: No such file or directory
2022-04-22T00:25:04.000 [info] chmod: /data/git/: No such file or directory
2022-04-22T00:25:04.000 [info] 2022/04/22 00:25:04 [ WARN] Custom config "/data/gogs/conf/app.ini" not found. Ignore this warning if you're running for the first time
2022-04-22T00:25:04.000 [info] 2022/04/22 00:25:04 [FATAL] [gogs.io/gogs/internal/cmd/web.go:165 runWeb()] Failed to initialize application: init configuration: create SSH root directory: mkdir /data: permission denied
2022-04-22T00:25:05.000 [info] Saving key "/data/ssh/ssh_host_rsa_key" failed: No such file or directory
2022-04-22T00:25:05.000 [info] Saving key "/data/ssh/ssh_host_dsa_key" failed: No such file or directory
2022-04-22T00:25:05.000 [info] Saving key "/data/ssh/ssh_host_ecdsa_key" failed: No such file or directory
2022-04-22T00:25:05.000 [info] Saving key "/data/ssh/ssh_host_ed25519_key" failed: No such file or directory
2022-04-22T00:25:05.000 [info] chown: /data/ssh/*: No such file or directory
2022-04-22T00:25:05.000 [info] chmod: /data/ssh: No such file or directory
2022-04-22T00:25:05.000 [info] chmod: /data/ssh/*: No such file or directory
2022-04-22T00:25:05.000 [info] Unable to load host key: /data/ssh/ssh_host_rsa_key
2022-04-22T00:25:05.000 [info] Unable to load host key: /data/ssh/ssh_host_dsa_key
2022-04-22T00:25:05.000 [info] Unable to load host key: /data/ssh/ssh_host_ecdsa_key
2022-04-22T00:25:05.000 [info] Unable to load host key: /data/ssh/ssh_host_ed25519_key
2022-04-22T00:25:05.000 [info] sshd: no hostkeys available -- exiting.
2022-04-22T00:25:06.000 [info] Saving key "/data/ssh/ssh_host_dsa_key" failed: No such file or directory
2022-04-22T00:25:06.000 [info] Unable to load host key: /data/ssh/ssh_host_ecdsa_key
2022-04-22T00:25:06.000 [info] sshd: no hostkeys available -- exiting.
***v0 failed - Failed due to unhealthy allocations - no stable job version to auto revert to and deploying as v1

Troubleshooting guide at https://fly.io/docs/getting-started/troubleshooting/
Error abort
```

Reading the Dockerfile: https://hub.docker.com/r/gogs/gogs ⏳

**Comment by nelsonic** [comment]
Working: https://gogs-server.fly.dev/
![image](https://user-images.githubusercontent.com/194400/164580821-919aff0c-4656-4520-83b8-1e3c12e5620c.png)

https://gogs-server.fly.dev/nelsonic/public-repo
![image](https://user-images.githubusercontent.com/194400/164581017-247d388b-0ed5-475a-960d-55140247e47c.png)

**Comment by nelsonic** [comment]
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/194400/164786677-18901fe2-1c38-4419-b63f-395ba9ff6d9e.png">

**Comment by nelsonic** [comment]
Tried:
```
flyctl ssh console
```
got:
```sh
Error host unavailable: host was not found in DNS

**Comment by nelsonic** [comment]
Ongoing issue with hosts not resolving in the `lhr` (London) region:
https://community.fly.io/t/phoenix-deploy-using-fly-launch/4858/2

**Comment by nelsonic** [comment]
Dropped an update on: https://community.fly.io/t/gogs-standalone-git-service-as-a-fly-example/358/2 thanking @codepope for his great guide and hopefully helping others with their setup/journey. 🤞

**Comment by nelsonic** [comment]
```sh
git clone ssh://git@gogs-server.fly.dev:10022/nelsonic/public-repo.git
```

That worked!

```sh
Cloning into 'public-repo'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
Receiving objects: 100% (5/5), 6.62 KiB | 6.62 MiB/s, done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
```

Update the `README.md` on my Mac:

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/194400/165000134-7adfe672-01cf-4637-bb71-02c95e58709a.png">


`git commit` and `git push` the code:

```sh
git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 350 bytes | 350.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
To ssh://gogs-server.fly.dev:10022/nelsonic/public-repo.git
   7f92c5d..f714a64  master -> master
``` 

https://gogs-server.fly.dev/nelsonic/public-repo
![image](https://user-images.githubusercontent.com/194400/165000085-de1166d1-6f89-4dc9-9c47-aae89fca9003.png)

 

Branches work:
![image](https://user-images.githubusercontent.com/194400/164999937-ac78290e-5d09-4016-8b26-252a1134ba98.png)

Here is the content on the `draft` branch:
![image](https://user-images.githubusercontent.com/194400/164999949-d0076a91-3cf5-417d-8944-82861e2e39d7.png)

**Comment by nelsonic** [comment]
![gogs-fly-config-1of-2](https://user-images.githubusercontent.com/194400/165000531-6e352107-860b-4bb2-ad29-4f172f6fc08d.png)
![gogs-fly-config-2of-2](https://user-images.githubusercontent.com/194400/165000528-79275762-f070-4bf0-b440-5a0fbf1ba9bc.png)

**Comment by nelsonic** [comment]
Stoked this is working! 🎉  https://github.com/dwyl/gogs-server

**Comment by nelsonic** [comment]
Next: https://github.com/dwyl/gogs/issues/7
