### ISSUE TITLE
Fly.io Review Apps

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#85]
On a recent client project we had Heroku Review Apps working.  ✅ 
But weren't able to get Fly.io Review Apps working ... 😞 
We need this for testing/QA-ing PRs in our App that create new features. 📱 

# Todo

+ [ ] Check https://github.com/superfly/fly-pr-review-apps to see if it's in a _useful_ state. 👀 🤞 
+ [ ] Attempt to implement it for one of our projects e.g: **`MVP`** 🧑‍💻 
+ [ ] Document each step of the way in a new file: `fly-review-apps.md` 📝

**Comment by SimonLab** [comment]
Installation documentation from the Github marketplace: https://github.com/marketplace/actions/pr-review-apps-on-fly-io

![image](https://user-images.githubusercontent.com/6057298/205949421-e0ff1929-7ffb-4438-a74d-deac42a8150f.png)

**Comment by nelsonic** [comment]
If it's that simple I will be very impressed. 🤞
