### ISSUE TITLE
Deploy Managed `Postgres` on `DigitalOcean` :shipit: 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#90]
In light of `Fly.io` losing all our data for _both_ `Auth` https://github.com/dwyl/auth/issues/325 and the `MVP` https://github.com/dwyl/mvp/issues/449#issuecomment-2094578288 
I've decided we won't be using their platform anymore. ***EVER***!! 😡 

Instead, going to use https://www.digitalocean.com/products/managed-databases-postgresql
Because we can have an unlimited databases (with small amounts of data) in the same cluster:
https://www.digitalocean.com/community/questions/how-many-databases-can-i-create-for-15
<img width="755" alt="image" src="https://github.com/dwyl/learn-devops/assets/194400/78df8a47-c66a-4824-b946-cde1ac787707">

Pricing: https://www.digitalocean.com/pricing/managed-databases at the time of writing **`$15/month`**
<img width="1444" alt="image" src="https://github.com/dwyl/learn-devops/assets/194400/207f26b8-4e24-4a92-8ebb-fc9b859eb982">

# Todo

+ [ ] Record Screen while doing all the setup!
+ [ ] Setup the DB!
+ [ ] Create a Test DB
+ [ ] Add some data
+ [ ] Retrieve the data
+ [ ] Explore the point-in-time recovery 

# Next

+ [ ] Deploying a Phoenix Application to Digital Ocean: https://www.youtube.com/watch?v=Dw7RPqSIv-0
  + [ ] https://github.com/or-equals/liveview_mastery/pull/11/files

**Comment by nelsonic** [comment]
For the record: before embarking on this, we did a quick check of the `Fly.io` docs: 
https://fly.io/docs/postgres/advanced-guides/high-availability-and-global-replication
To _confirm_ they haven't changed their stance on having _managed_ `Postgres` ...
Sadly, they haven't changed their stance on _managed_ service:
https://fly.io/docs/postgres/getting-started/what-you-should-know/

<img width="926" alt="image" src="https://github.com/user-attachments/assets/58fe962e-a271-4124-a0eb-edfc63433548">

It's still very much a "manage you own with our tools" ...
And as we've experienced, that's not fun when the machine crashes.

Their approach to high availability is still _manual_:
https://fly.io/docs/postgres/advanced-guides/high-availability-and-global-replication/
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/0bcd482e-7010-4afd-bb1a-b86bcafd99fa">

They are open about this approach not being good for write-heavy apps and those with long-lived connections:
https://fly.io/docs/postgres/advanced-guides/high-availability-and-global-replication/#this-is-wrong-for-some-apps
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/1827a91f-e67a-4a08-a9fe-6e7a0a88eb76">

Doc snapshot: [eb45cbf/postgres/advanced-guides/high-availability-and-global-replication.html.markerb](https://github.com/superfly/docs/blob/50f571d8c0ae0928d2f2a043fec18f8d00f4f4e5/postgres/advanced-guides/high-availability-and-global-replication.html.markerb)

So with that, I feel like I'm left with no choice but to switch (the DB) to `DigitalOcean` **_Managed_ Postgres**.

**Comment by nelsonic** [comment]
The "_problem_" with **`DigitalOcean` _Managed_ Postgres**: https://www.digitalocean.com/pricing/managed-databases#postgresql is that the _cheapest_ instance **`$15/month`** is a total bait-and-switch!
<img width="1273" alt="image" src="https://github.com/user-attachments/assets/2c7d5406-f15b-47e2-a457-a6ffa82d38b5">
The moment you want multiple instances for failover, they bump the instance from `1GB RAM` to `2GB RAM`  and `10GB SSD` to `30GB SSD` i.e. not even "high availability", just a backup instance, ***quadruples*** the price!!

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/449620f0-485d-447e-8b9f-221314efc0ec">

We only _care_ about this while _developing_ an App because it's **`$60/month x 12 month = $720/year`** ... 💸 

And if/when you need to scale (_vertically_) the max is: `256 GiB RAM` and `15TB SSD` for **`$16,494/month`**:
<img width="1273" alt="image" src="https://github.com/user-attachments/assets/a0d080aa-2e38-4f50-a659-0ea263f7ab8e">

Nobody is going to spend this much without having the _revenue_ to cover it. 💰 
Cough-cough except _every_ "AI" company spending 100x this on training models with no path to profitability ... 😜 
That's "VC Money" it's not _real_. Anyway ... 🤐

**Comment by nelsonic** [comment]
PR `in-progress`: https://github.com/dwyl/learn-devops/pull/92 🧑‍💻 ⏳

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/learn-devops/issues/93 ⏳

**Comment by nelsonic** [comment]
Given that connecting from `Fly.io` to `DigitalOcean` was a dead-end https://github.com/dwyl/learn-devops/issues/93#issuecomment-2425376030 we need to decide if we are going to use `DigitalOcean` for our `Apps` or if we should consider something more self-managed e.g: `Hetzner` #97 💭 

The "hard" part is the `Postgres`, we need High Availability (continuous backups) and ideally _fast/cheap_ storage.
`DigitalOcean` is _silly_ expensive as noted above https://github.com/dwyl/learn-devops/issues/90#issuecomment-2241488297 the price _accelerates_ rather than passing economies of scale back to the customer. 📈 💸 
_Obviously_ reaching the sort of scale where paying for serious `Postgres` resources are [champagne problems](https://en.wiktionary.org/wiki/champagne_problem).
but I still find it _absurd_ to pay `$16k/month` for something that would cost `~€2k` on `Hetzner`! 🤯 💰 🔥 
https://www.hetzner.com/dedicated-rootserver

<img width="856" alt="image" src="https://github.com/user-attachments/assets/ea02066d-99cc-4c06-bd98-b8d7d87d9d70">

This is still an expensive machine! But there is simply no comparison! it's 1/8 the price!! 
Sooooo ... this is what I'm thinking: https://github.com/dwyl/mvp/issues/488#issuecomment-2472209687

**Comment by nelsonic** [comment]
This would have been cheaper than https://github.com/dwyl/learn-postgresql/issues/121 in the _short_ term ... 💸 🤦‍♂ 
Closing as not using DO.
