### ISSUE TITLE
Deploy `Phoenix` App to `DigitalOcean`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#94]
Opening this issue as a reminder to capture/document how to deploy an `Elixir/Phoenix` App to `DigitalOcean`. 🚀 
Don't have time to focus on this right now, but will return to it on weekend when kids are asleep. 🛌 

# Todo

+ [ ] Research existing posts/videos on this topic. 🔍 
+ [ ] Synthesise existing knowledge 📝 
+ [ ] Attempt to replicate it for our `MVP` App. 🤞

**Comment by nelsonic** [comment]
https://elixirforum.com/t/deploy-your-phoenix-app-on-digitalocean-in-30-minutes/65738

![480p](https://github.com/user-attachments/assets/fb6ee785-7808-45eb-8509-97d42bcdefce)

https://pdgonzalez872.github.io/articles/012_20210311_deploy_phoenix_bare_metal.html

**Comment by nelsonic** [comment]
Creating a new basic droplet (`VM`) on `DigitalOcean` to attempt this:

<img src="https://github.com/user-attachments/assets/f73f8e8a-5dd4-4bbd-a414-1f3e80cfed67" />

`Debian` because it has less bloat and no upsell.
Ref: https://www.reddit.com/r/debian/comments/16edphm/why_debian_always_faster_than_ubuntu/

**Comment by nelsonic** [comment]
Re-watching the `Kamal` setup video. ⏳

**Comment by nelsonic** [comment]
Re-watched the `Kamal` intro video from DHH. 📺 ⏳ 
What they've done looks _decent_ but, like `Rails` there's quite a lot of "magic". 🪄 
But I'm not super keen on letting `Kamal` run my `Postgres` in a `Docker` container ... 🙃 
and reading the https://github.com/basecamp/kamal/discussions on `GitHub`

<img src="https://github.com/user-attachments/assets/45b69b3f-0106-4360-aefc-18e7bbd72a55" />

The top discussion is: 
https://github.com/basecamp/kamal/discussions/1823

<img  src="https://github.com/user-attachments/assets/ed4ec835-5be2-4733-8ac8-189765e1df9d" />

This all coupled with the requirement to use `Ubuntu` as the server (when I _really_ want to use `OpenBSD`) means I'm considering other options. 💭

**Comment by nelsonic** [comment]
GOTO: https://www.reddit.com/r/elixir/comments/1qd92pj/deploying_elixir/
