### ISSUE TITLE
How to Backup Fly.io Postgres Instance?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#95]
# Todo

+ [ ] backup the Fly.io Postgres instance. 
+ [ ] restore on DigitalOcean
+ [ ] Connect hits.dwyl.com to the DigitalOcean DB #93

**Comment by nelsonic** [comment]
`T2h` because the side-quest #93 is still an unknown. 🙃 
Might be a couple of mins. but might also be impossible. 🤷‍♂️

**Comment by nelsonic** [comment]
https://tello.io/blog/flyio-dump-your-postgresql-db-locally

**Comment by nelsonic** [comment]
Currently getting the following error:

```sh
psql: error: connection to server at "10.0.1.4", port 6432 failed: FATAL:  SASL authentication failed
```
